spring:
  security:
    oauth2:
#      client:
#        registration:
#          keycloak:
#            client-id: my-spring-app                 # Matches the clientId in Keycloak
#            client-secret: myCustomSecret123!        # Matches the client secret in Keycloak
#            scope: openid, profile, email
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8081/realms/geo-tracking-solution   # Your Keycloak realm's issuer URI
#            user-info-uri: http://localhost:8081/realms/geo-tracking.solution/protocol/openid-connect/userinfo
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8081/realms/geo-tracking-solution"

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG

keycloak:
  auth-server-url: http://localhost:8081
  realm: geo-tracking-solution
  client-id: java-spring
  client-secret: OySDKuu1HlxIW2c4Ptk4wOsfMZ8vljhb
